language: node_js
node_js:
  - 16
dist: xenial
sudo: required
addons:
  sonarcloud:
    organization: "sgryts"
branches:
  only:
    - main
before_script:
  - npm install
script:
  - npm run snyk:test
  - npm run lint
  - npm run test:ci-coverage
  - sonar-scanner
after_success:
  - npm run snyk:monitor
