language: node_js
node_js:
  - 16
dist: trusty
sudo: required
branches:
  only:
    - main
before_script:
  - npm install
script:
  - npm run test:headless
notifications:
  email:
    on_failure: change
    on_success: change
