language: node_js
node_js:
  - 16
dist: xenial
sudo: required
addons:
  sonarcloud:
    organization: "Sgryts"
branches:
  only:
    - main
before_script:
  - npm install
script:
  - npm run test:ci-coverage
  - sonar-scanner
